dashboard_top:
    path: /home
    controller: App\Controller\DashboardController::home

user_signup:
    path: /signup
    controller: App\Controller\UserController::signup

user_signin:
    path: /signin
    controller: App\Controller\UserController::signin