dashboard_top:
    path: /
    controller: App\Controller\DashboardController::top

dashboard_home:
    path: /home
    controller: App\Controller\DashboardController::home

user_signup:
    path: /signup
    controller: App\Controller\UserController::signup

user_signin:
    path: /signin
    controller: App\Controller\UserController::signin

expense_transaction_index:
    path: /expense
    controller: App\Controller\ExpenseTransactionController::index

expense_transaction_create:
    path: /expense/create
    controller: App\Controller\ExpenseTransactionController::create